# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gr00t.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gr00t.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgr00t.proto\x12\x05gr00t\"\x92\x01\n\x0cInferRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x13\n\x0binstruction\x18\x02 \x01(\t\x12\x10\n\x08left_arm\x18\x03 \x03(\x02\x12\x11\n\tright_arm\x18\x04 \x03(\x02\x12\x11\n\tleft_hand\x18\x05 \x03(\x02\x12\x12\n\nright_hand\x18\x06 \x03(\x02\x12\r\n\x05waist\x18\x07 \x03(\x02\"\x83\x01\n\rInferResponse\x12=\n\raction_chunks\x18\x01 \x03(\x0b\x32&.gr00t.InferResponse.ActionChunksEntry\x1a\x33\n\x11\x41\x63tionChunksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\x0f\n\rHealthRequest\"7\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x14\n\x0cmodel_loaded\x18\x02 \x01(\x08\x32{\n\x0eGR00TInference\x12\x32\n\x05Infer\x12\x13.gr00t.InferRequest\x1a\x14.gr00t.InferResponse\x12\x35\n\x06Health\x12\x14.gr00t.HealthRequest\x1a\x15.gr00t.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gr00t_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERRESPONSE_ACTIONCHUNKSENTRY']._loaded_options = None
  _globals['_INFERRESPONSE_ACTIONCHUNKSENTRY']._serialized_options = b'8\001'
  _globals['_INFERREQUEST']._serialized_start=23
  _globals['_INFERREQUEST']._serialized_end=169
  _globals['_INFERRESPONSE']._serialized_start=172
  _globals['_INFERRESPONSE']._serialized_end=303
  _globals['_INFERRESPONSE_ACTIONCHUNKSENTRY']._serialized_start=252
  _globals['_INFERRESPONSE_ACTIONCHUNKSENTRY']._serialized_end=303
  _globals['_HEALTHREQUEST']._serialized_start=305
  _globals['_HEALTHREQUEST']._serialized_end=320
  _globals['_HEALTHRESPONSE']._serialized_start=322
  _globals['_HEALTHRESPONSE']._serialized_end=377
  _globals['_GR00TINFERENCE']._serialized_start=379
  _globals['_GR00TINFERENCE']._serialized_end=502
# @@protoc_insertion_point(module_scope)
