# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gr00t_pb2 as gr00t__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gr00t_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GR00TInferenceStub(object):
    """GR00T N1.6 원격 추론 서비스
    2026-04-12: ZMQ 방식 → gRPC 재설계 (NLB + mTLS 지원)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/gr00t.GR00TInference/Infer',
                request_serializer=gr00t__pb2.InferRequest.SerializeToString,
                response_deserializer=gr00t__pb2.InferResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/gr00t.GR00TInference/Health',
                request_serializer=gr00t__pb2.HealthRequest.SerializeToString,
                response_deserializer=gr00t__pb2.HealthResponse.FromString,
                _registered_method=True)


class GR00TInferenceServicer(object):
    """GR00T N1.6 원격 추론 서비스
    2026-04-12: ZMQ 방식 → gRPC 재설계 (NLB + mTLS 지원)
    """

    def Infer(self, request, context):
        """로봇 관절 액션 추론
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """서버 / 모델 로드 상태 확인
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GR00TInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=gr00t__pb2.InferRequest.FromString,
                    response_serializer=gr00t__pb2.InferResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=gr00t__pb2.HealthRequest.FromString,
                    response_serializer=gr00t__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gr00t.GR00TInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gr00t.GR00TInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GR00TInference(object):
    """GR00T N1.6 원격 추론 서비스
    2026-04-12: ZMQ 방식 → gRPC 재설계 (NLB + mTLS 지원)
    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gr00t.GR00TInference/Infer',
            gr00t__pb2.InferRequest.SerializeToString,
            gr00t__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gr00t.GR00TInference/Health',
            gr00t__pb2.HealthRequest.SerializeToString,
            gr00t__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
